import fs from 'node:fs/promises';

// Map from killStatsName => prettyName.
const normalizedToPrettyNames = new Map([
	// Bosses and boss-like creatures.
	['A Greedy Eye', 'A Greedy Eye'],
	['A Shielded Astral Glyph', 'A Shielded Astral Glyph'],
	['Abyssador', 'Abyssador'],
	['Achad', 'Achad'],
	['Aftershock', 'Aftershock'],
	['Alptramun', 'Alptramun'],
	['Amenef the Burning', 'Amenef the Burning'],
	['An Astral Glyph', 'An Astral Glyph'],
	['An Observer Eye', 'An Observer Eye'],
	['Ancient Spawn Of Morgathla', 'Ancient Spawn of Morgathla'],
	['Anmothra', 'Anmothra'],
	['Annihilon', 'Annihilon'],
	['Anomaly', 'Anomaly'],
	['Apprentice Sheng', 'Apprentice Sheng'],
	['Arachir the Ancient One', 'Arachir the Ancient One'],
	['Armenius', 'Armenius'],
	['Arthei', 'Arthei'],
	['Arthom The Hunter', 'Arthom the Hunter'],
	['Ascending Ferumbras', 'Ascending Ferumbras'],
	['Ashmunrah', 'Ashmunrah'],
	['Avalanche', 'Avalanche'],
	['Axeitus Headbanger', 'Axeitus Headbanger'],
	['Azerus', 'Azerus'],
	['Barbaria', 'Barbaria'],
	['Baron Brute', 'Baron Brute'],
	['Battlemaster Zunzu', 'Battlemaster Zunzu'],
	['Bibby Bloodbath', 'Bibby Bloodbath'],
	['Big Boss Trolliver', 'Big Boss Trolliver'],
	['Black Knights', 'Black Knight'],
	['Black Vixen', 'Black Vixen'],
	['Bloodback', 'Bloodback'],
	['Bloodpaw', 'Bloodpaw'],
	['Bone Capsule', 'Bone Capsule'],
	['Boogey', 'Boogey'],
	['Boreth', 'Boreth'],
	['Bovinus', 'Bovinus'],
	['Bragrumol', 'Bragrumol'],
	['Brain Head', 'Brain Head'],
	['Bretzecutioner', 'Bretzecutioner'],
	['Brokul', 'Brokul'],
	['Brother Chill', 'Brother Chill'],
	['Brother Freeze', 'Brother Freeze'],
	['Brother Worm', 'Brother Worm'],
	['Bruise Payne', 'Bruise Payne'],
	['Brutus Bloodbeard', 'Brutus Bloodbeard'],
	['Bullwark', 'Bullwark'],
	['Burster', 'Burster'],
	['Captain Jones', 'Captain Jones'],
	['Cave Spiders', 'Cave Spider'],
	['Channeling Earl Osam', 'Channeling Earl Osam'],
	['Charged Anomaly', 'Charged Anomaly'],
	['Chikhaton', 'Chikhaton'],
	['Chizzoron the Distorter', 'Chizzoron the Distorter'],
	['Chopper', 'Chopper'],
	['Coldheart', 'Coldheart'],
	['Colerian the Barbarian', 'Colerian the Barbarian'],
	['Count Vlarkorth', 'Count Vlarkorth'],
	['Countess Sorrow', 'Countess Sorrow'],
	['Cublarc the Plunderer', 'Cublarc the Plunderer'],
	['Cursed Gladiators', 'Cursed Gladiator'],
	['Custodian', 'Custodian'],
	['Damage Resonance', 'Damage Resonance'],
	['Darakan the Executioner', 'Darakan the Executioner'],
	['Darkfang', 'Darkfang'],
	['Dazed Leaf Golems', 'Dazed Leaf Golem'],
	['Deadeye Devious', 'Deadeye Devious'],
	['Death Priest Shargon', 'Death Priest Shargon'],
	['Deathbine', 'Deathbine'],
	['Deathbringer', 'Deathbringer'],
	['Deathstrike', 'Deathstrike'],
	['Deep Terror', 'Deep Terror'],
	['Demodras', 'Demodras'],
	['Despair', 'Despair'],
	['Destabilized Ferumbras', 'Destabilized Ferumbras'],
	['Devovorga', 'Devovorga'],
	['Dharalion', 'Dharalion'],
	['Diblis the Fair', 'Diblis the Fair'],
	['Dipthrah', 'Dipthrah'],
	['Dirtbeard', 'Dirtbeard'],
	['Diseased Bills', 'Diseased Bill'],
	['Diseased Dans', 'Diseased Dan'],
	['Diseased Freds', 'Diseased Fred'],
	['Doctor Perhaps', 'Doctor Perhaps'],
	['Doomhowl', 'Doomhowl'],
	['Dorokoll The Mystic', 'Dorokoll the Mystic'],
	['Dracola', 'Dracola'],
	['Dragonking Zyrtarch', 'Dragonking Zyrtarch'],
	['Drasilla', 'Drasilla'],
	['Dreadful Disruptor', 'Dreadful Disruptor'],
	['Dreadmaw', 'Dreadmaw'],
	['Dreadwing', 'Dreadwing'],
	['Drume', 'Drume'],
	['Duke Krule', 'Duke Krule'],
	['Earl Osam', 'Earl Osam'],
	['Earth Overlords', 'Earth Overlord'],
	['Ekatrix', 'Ekatrix'],
	['Eliz The Unyielding', 'Eliz the Unyielding'],
	['Elvira Hammerthrust', 'Elvira Hammerthrust'],
	['Energy Overlords', 'Energy Overlords'],
	['Enusat the Onyx Wing', 'Enusat the Onyx Wing'],
	['Eradicator', 'Eradicator'],
	['Eshtaba The Conjurer', 'Eshtaba the Conjurer'],
	['Esmeralda', 'Esmeralda'],
	['Essence Of Malice', 'Essence of Malice'],
	['Ethershreck', 'Ethershreck'],
	['Evil Mastermind', 'Evil Mastermind'],
	['Faceless Bane', 'Faceless Bane'],
	['Fahim the Wise', 'Fahim the Wise'],
	['Fallen Mooh\'Tah Master Ghar', 'Fallen Mooh\'Tah Master Ghar'],
	['Fatality', 'Fatality'],
	['Fazzrah', 'Fazzrah'],
	['Fernfang', 'Fernfang'],
	['Feroxa', 'Feroxa'],
	['Ferumbras Mortal Shell', 'Ferumbras Mortal Shell'],
	['Ferumbras Soul Splinter', 'Ferumbras Soul Splinter'],
	['Ferumbras', 'Ferumbras'],
	['Fire Overlords', 'Fire Overlords'],
	['Flameborn', 'Flameborn'],
	['Flamecaller Zazrak', 'Flamecaller Zazrak'],
	['Fleabringer', 'Fleabringer'],
	['Fleshcrawler', 'Fleshcrawler'],
	['Fleshslicer', 'Fleshslicer'],
	['Foreman Kneebiter', 'Foreman Kneebiter'],
	['Foreshock', 'Foreshock'],
	['Frenzy', 'Frenzy'],
	['Frostfur', 'Frostfur'],
	['Fugue', 'Fugue'],
	['Furious Scorpions', 'Furious Scorpions'],
	['Furyosa', 'Furyosa'],
	['Gaffir', 'Gaffir'],
	['Gaz\'haragoth', 'Gaz\'haragoth'],
	['General Murius', 'General Murius'],
	['Ghazbaran', 'Ghazbaran'],
	['Ghulosh\' Deathgaze', 'Ghulosh\' Deathgaze'],
	['Ghulosh', 'Ghulosh'],
	['Glitterscale', 'Glitterscale'],
	['Glooth Fairy', 'Glooth Fairy'],
	['Gnomevil', 'Gnomevil'],
	['Gnorre Chyllson', 'Gnorre Chyllson'],
	['Golgordan', 'Golgordan'],
	['Gorgo', 'Gorgo'],
	['Gorzindel', 'Gorzindel'],
	['Goshnar\'s Cruelty', 'Goshnar\'s Cruelty'],
	['Goshnar\'s Greed', 'Goshnar\'s Greed'],
	['Goshnar\'s Hatred', 'Goshnar\'s Hatred'],
	['Goshnar\'s Malice', 'Goshnar\'s Malice'],
	['Goshnar\'s Megalomania', 'Goshnar\'s Megalomania'],
	['Goshnar\'s Spite', 'Goshnar\'s Spite'],
	['Grand Canon Dominus', 'Grand Canon Dominus'],
	['Grand Chaplain Gaunder', 'Grand Chaplain Gaunder'],
	['Grand Commander Soeren', 'Grand Commander Soeren'],
	['Grand Master Oberon', 'Grand Master Oberon'],
	['Grand Mother Foulscale', 'Grand Mother Foulscale'],
	['Grandfather Tridian', 'Grandfather Tridian'],
	['Gravelord Oshuran', 'Gravelord Oshuran'],
	['Greed', 'Greed'],
	['Grimgor Guteater', 'Grimgor Guteater'],
	['Groam', 'Groam'],
	['Grorlam', 'Grorlam'],
	['Guard Captain Quaid', 'Guard Captain Quaid'],
	['Guilt', 'Guilt'],
	['Hairman the Huge', 'Hairman the Huge'],
	['Hatebreeder', 'Hatebreeder'],
	['Haunter', 'Haunter'],
	['Hellgorak', 'Hellgorak'],
	['Hemming', 'Hemming'],
	['Heoni', 'Heoni'],
	['Hide', 'Hide'],
	['High Templar Cobrass', 'High Templar Cobrass'],
	['Hirintror', 'Hirintror'],
	['Horadron', 'Horadron'],
	['Horestis', 'Horestis'],
	['Ice Overlords', 'Ice Overlords'],
	['Incineron', 'Incineron'],
	['Inky', 'Inky'],
	['Irahsae', 'Irahsae'],
	['Irgix the Flimsy', 'Irgix the Flimsy'],
	['Izcandar Champion of Summer', 'Izcandar Champion of Summer'],
	['Izcandar Champion of Winter', 'Izcandar Champion of Winter'],
	['Izcandar the Banished', 'Izcandar the Banished'],
	['Jailer', 'Jailer'],
	['Jaul', 'Jaul'],
	['Jesse the Wicked', 'Jesse the Wicked'],
	['Katex Blood Tongue', 'Katex Blood Tongue'],
	['Kerberos', 'Kerberos'],
	['Kesar', 'Kesar'],
	['King Zelos', 'King Zelos'],
	['Koshei the Deathless', 'Koshei the Deathless'],
	['Kraknaknork', 'Kraknaknork'],
	['Kraknaknork\'s Demon', 'Kraknaknork\'s Demon'],
	['Kreebosh the Exile', 'Kreebosh the Exile'],
	['Kroazur', 'Kroazur'],
	['Kusuma', 'Kusuma'],
	['Lady Tenebris', 'Lady Tenebris'],
	['Last Planegazer', 'Last Planegazer'],
	['Latrivan', 'Latrivan'],
	['Leiden', 'Leiden'],
	['Lersatio', 'Lersatio'],
	['Lethal Lissy', 'Lethal Lissy'],
	['Leviathan', 'Leviathan'],
	['Lisa', 'Lisa'],
	['Lizard Abomination', 'Lizard Abomination'],
	['Lizard Gate Guardians', 'Lizard Gate Guardian'],
	['Lloyd', 'Lloyd'],
	['Lokathmor', 'Lokathmor'],
	['Lord Azaram', 'Lord Azaram'],
	['Lord of the Elements', 'Lord of the Elements'],
	['Mad Mages', 'Mad Mage'],
	['Mad Technomancers', 'Mad Technomancer'],
	['Madareth', 'Madareth'],
	['magma bubbles', 'Magma Bubble'],
	['Mahatheb', 'Mahatheb'],
	['Mahrdis', 'Mahrdis'],
	['Malkhar Deathbringer', 'Malkhar Deathbringer'],
	['Malofur Mangrinder', 'Malofur Mangrinder'],
	['Mamma Longlegs', 'Mamma Longlegs'],
	['Man in the Cave', 'Man in the Cave'],
	['Marziel', 'Marziel'],
	['Massacre', 'Massacre'],
	['Maw', 'Maw'],
	['Mawhawk', 'Mawhawk'],
	['Maxxenius', 'Maxxenius'],
	['Mazoran', 'Mazoran'],
	['Mazzinor', 'Mazzinor'],
	['Megasylvan Yselda', 'Megasylvan Yselda'],
	['Melting Frozen Horrors', 'Melting Frozen Horror'],
	['Menace', 'Menace'],
	['Mephiles', 'Mephiles'],
	['Merikh the Slaughterer', 'Merikh the Slaughterer'],
	['Mezlon The Defiler', 'Mezlon the Defiler'],
	['Mindmasher', 'Mindmasher'],
	['Monstor', 'Monstor'],
	['Mooh\'Tah Masters', 'Mooh\'Tah Master'],
	['Morgaroth', 'Morgaroth'],
	['Morguthis', 'Morguthis'],
	['Morik the Gladiator', 'Morik the Gladiator'],
	['Mornenion', 'Mornenion'],
	['Morshabaal', 'Morshabaal'],
	['Mozradek', 'Mozradek'],
	['Mr. Punish', 'Mr. Punish'],
	['Munster', 'Munster'],
	['Mutated Zalamon', 'Mutated Zalamon'],
	['Necropharus', 'Necropharus'],
	['Neferi the Spy', 'Neferi the Spy'],
	['Norgle Glacierbeard', 'Norgle Glacierbeard'],
	['Obujos', 'Obujos'],
	['Ocyakao', 'Ocyakao'],
	['Omrafir', 'Omrafir'],
	['Omruc', 'Omruc'],
	['Oodok Witchmaster', 'Oodok Witchmaster'],
	['Orcus the Cruel', 'Orcus the Cruel'],
	['Orshabaal', 'Orshabaal'],
	['Outburst', 'Outburst'],
	['Owin', 'Owin'],
	['Paiz the Pauperizer', 'Paiz the Pauperizer'],
	['Phrodomo', 'Phrodomo'],
	['Plagirath', 'Plagirath'],
	['Plagueroot', 'Plagueroot'],
	['Planestrider', 'Planestrider'],
	['Preceptor Lazare', 'Preceptor Lazare'],
	['Prince Drazzak', 'Prince Drazzak'],
	['Professor Maxxen', 'Professor Maxxen'],
	['Pythius the Rotten', 'Pythius the Rotten'],
	['Rage of Mazoran', 'Rage of Mazoran'],
	['Ragiaz', 'Ragiaz'],
	['Raging Mages', 'Raging Mage'],
	['Rahemos', 'Rahemos'],
	['Ratmiral Blackwhiskers', 'Ratmiral Blackwhiskers'],
	['Ravenous Hunger', 'Ravenous Hunger'],
	['Raxias', 'Raxias'],
	['Razzagorn', 'Razzagorn'],
	['Realityquake', 'Realityquake'],
	['Renegade Orcs', 'Renegade Orc'],
	['Ribstride', 'Ribstride'],
	['Robby the Reckless', 'Robby the Reckless'],
	['Rocko', 'Rocko'],
	['Rocky', 'Rocky'],
	['Ron the Ripper', 'Ron the Ripper'],
	['Rotspit', 'Rotspit'],
	['Rottie the Rotworm', 'Rottie the Rotworm'],
	['Rotworm Queens', 'Rotworm Queen'],
	['Rukor Zad', 'Rukor Zad'],
	['Rupture', 'Rupture'],
	['Scarlett Etzel', 'Scarlett Etzel'],
	['Shadow of Boreth', 'Shadow of Boreth'],
	['Shadow of Lersatio', 'Shadow of Lersatio'],
	['Shadow of Marziel', 'Shadow of Marziel'],
	['Shadowpelt', 'Shadowpelt'],
	['Shadowstalker', 'Shadowstalker'],
	['Shard of Corruption', 'Shard of Corruption'],
	['Shardhead', 'Shardhead'],
	['Sharpclaw', 'Sharpclaw'],
	['Sharptooth', 'Sharptooth'],
	['Shlorg', 'Shlorg'],
	['Shulgrax', 'Shulgrax'],
	['Sin Devourers', 'Sin Devourers'],
	['Sir Baeloc', 'Sir Baeloc'],
	['Sir Nictros', 'Sir Nictros'],
	['Sir Valorcrest', 'Sir Valorcrest'],
	['Sister Hetai', 'Sister Hetai'],
	['Slim', 'Slim'],
	['Smuggler Baron Silvertoe', 'Smuggler Baron Silvertoe'],
	['Snake Thing', 'Snake Thing'],
	['Solid Frozen Horrors', 'Solid Frozen Horror'],
	['Soul Cages', 'Soul Cages'],
	['Soul of Dragonking Zyrtarch', 'Soul of Dragonking Zyrtarch'],
	['spawns of the welter', 'Spawn of the Welter'],
	['Spirits of Earth', 'Spirits of Earth'],
	['Spirits of Fire', 'Spirits of Fire'],
	['Spirits of Water', 'Spirits of Water'],
	['spite of the emperor', 'Spite of the Emperor'],
	['Splasher', 'Splasher'],
	['Srezz Yellow Eyes', 'Srezz Yellow Eyes'],
	['Stonecracker', 'Stonecracker'],
	['Sulphur Scuttler', 'Sulphur Scuttler'],
	['Supercharged Mazzinor', 'Supercharged Mazzinor'],
	['Svoren the Mad', 'Svoren the Mad'],
	['Tanjis', 'Tanjis'],
	['Tarbaz', 'Tarbaz'],
	['Teleskor', 'Teleskor'],
	['Teneshpar', 'Teneshpar'],
	['tentacle of the Deep Terror', 'Tentacle of the Deep Terror'],
	['Tentugly', 'Tentugly'],
	['Terofar', 'Terofar'],
	['Thaian', 'Thaian'],
	['Thalas', 'Thalas'],
	['Thawing Dragon Lords', 'Thawing Dragon Lord'],
	['The Abomination', 'The Abomination'],
	['The Armored Voidborn', 'The Armored Voidborn'],
	['The Astral Source', 'The Astral Source'],
	['The Axeorcist', 'The Axeorcist'],
	['The Baron From Below', 'The Baron From Below'],
	['The Big Bad One', 'The Big Bad One'],
	['The Blazing Rose', 'The Blazing Rose'],
	['The Blightfather', 'The Blightfather'],
	['The Bloodtusk', 'The Bloodtusk'],
	['The Bloodweb', 'The Bloodweb'],
	['The Brainstealer', 'The Brainstealer'],
	['The Collector', 'The Collector'],
	['The Corruptor Of Souls', 'The Corruptor of Souls'],
	['The Count Of The Core', 'The Count of the Core'],
	['The Count', 'The Count'],
	['The Dark Dancer', 'The Dark Dancer'],
	['The Destruction', 'The Destruction'],
	['The Diamond Blossom', 'The Diamond Blossom'],
	['The Dread Maiden', 'The Dread Maiden'],
	['The Dreadorian', 'The Dreadorian'],
	['The Duke Of The Depths', 'The Duke of the Depths'],
	['The End Of Days', 'The End of Days'],
	['The Enraged Thorn Knight', 'The Enraged Thorn Knight'],
	['The Evil Eye', 'The Evil Eye'],
	['The False God', 'The False God'],
	['The Fear Feaster', 'The Fear Feaster'],
	['The Fire Empowered Duke', 'The Fire Empowered Duke'],
	['The Flaming Orchid', 'The Flaming Orchid'],
	['The Frog Prince', 'The Frog Prince'],
	['The Hag', 'The Hag'],
	['The Hairy One', 'The Hairy One'],
	['The Handmaiden', 'The Handmaiden'],
	['The Horned Fox', 'The Horned Fox'],
	['The Hunger', 'The Hunger'],
	['The Hungerer', 'The Hungerer'],
	['The Hungry Baron From Below', 'The Hungry Baron From Below'],
	['The Imperor', 'The Imperor'],
	['The Keeper', 'The Keeper'],
	['The Last Lore Keeper', 'The Last Lore Keeper'],
	['The Lily of Night', 'The Lily of Night'],
	['The Lord of the Lice', 'The Lord of the Lice'],
	['The Manhunter', 'The Manhunter'],
	['The Many', 'The Many'],
	['The Masked Marauder', 'The Masked Marauder'],
	['The Mean Masher', 'The Mean Masher'],
	['The Mega Magmaoid', 'The Mega Magmaoid'],
	['The Moonlight Aster', 'The Moonlight Aster'],
	['The Mutated Pumpkin', 'The Mutated Pumpkin'],
	['The Nightmare Beast', 'The Nightmare Beast'],
	['The Noxious Spawn', 'The Noxious Spawn'],
	['The Obliverator', 'The Obliverator'],
	['The Old Whopper', 'The Old Whopper'],
	['The Old Widow', 'The Old Widow'],
	['The Pale Count', 'The Pale Count'],
	['The Pale Worm', 'The Pale Worm'],
	['The Pit Lord', 'The Pit Lord'],
	['The Plasmother', 'The Plasmother'],
	['the primal menace', 'The Primal Menace'],
	['The Rage', 'The Rage'],
	['The Ravager', 'The Ravager'],
	['The Remorseless Corruptor', 'The Remorseless Corruptor'],
	['The Sandking', 'The Sandking'],
	['The Scourge Of Oblivion', 'The Scourge of Oblivion'],
	['The Shatterer', 'The Shatterer'],
	['The Sinister Hermit', 'The Sinister Hermit'],
	['The Snapper', 'The Snapper'],
	['The Souldespoiler', 'The Souldespoiler'],
	['The Source Of Corruption', 'The Source of Corruption'],
	['The Spellstealer', 'The Spellstealer'],
	['The Time Guardian', 'The Time Guardian'],
	['The Unarmored Voidborn', 'The Unarmored Voidborn'],
	['The Unwelcome', 'The Unwelcome'],
	['The Voice Of Ruin', 'The Voice of Ruin'],
	['The Weakened Count', 'The Weakened Count'],
	['The Welter', 'The Welter'],
	['The Winter Bloom', 'The Winter Bloom'],
	['Thul', 'Thul'],
	['Timira the Many-Headed', 'Timira the Many-Headed'],
	['Tiquandas Revenge', 'Tiquandas Revenge'],
	['Tirecz', 'Tirecz'],
	['Tormentor', 'Tormentor'],
	['Tremorak', 'Tremorak'],
	['Tromphonyte', 'Tromphonyte'],
	['Tyrn', 'Tyrn'],
	['Tzumrah The Dazzler', 'Tzumrah the Dazzler'],
	['Unaz the Mean', 'Unaz the Mean'],
	['Ungreez', 'Ungreez'],
	['Urmahlullu the Immaculate', 'Urmahlullu the Immaculate'],
	['Urmahlullu the Tamed', 'Urmahlullu the Tamed'],
	['Urmahlullu the Weakened', 'Urmahlullu the Weakened'],
	['Ushuriel', 'Ushuriel'],
	['Utua Stone Sting', 'Utua Stone Sting'],
	['Vashresamun', 'Vashresamun'],
	['Versperoth', 'Versperoth'],
	['Vok the Freakish', 'Vok the Freakish'],
	['Warlord Ruzad', 'Warlord Ruzad'],
	['Webster', 'Webster'],
	['White Pale', 'White Pale'],
	['Wildness of Urmahlullu', 'Wildness of Urmahlullu'],
	['Willi Wasp', 'Willi Wasp'],
	['Wisdom of Urmahlullu', 'Wisdom of Urmahlullu'],
	['World Devourer', 'World Devourer'],
	['wrath of the emperor', 'Wrath of the Emperor'],
	['Xenia', 'Xenia'],
	['Xogixath', 'Xogixath'],
	['Yaga the Crone', 'Yaga the Crone'],
	['Yakchal', 'Yakchal'],
	['Yalaharis', 'Yalaharis'],
	['Yirkas Blue Scales', 'Yirkas Blue Scales'],
	['Zamulosh', 'Zamulosh'],
	['Zanakeph', 'Zanakeph'],
	['Zarabustor', 'Zarabustor'],
	['Zarcorix Of Yalahar', 'Zarcorix of Yalahar'],
	['Zavarash', 'Zavarash'],
	['Zevelon Duskbringer', 'Zevelon Duskbringer'],
	['Zomba', 'Zomba'],
	['Zugurosh', 'Zugurosh'],
	['Zulazza the Corruptor', 'Zulazza the Corruptor'],
	['Zushuka', 'Zushuka'],

	// Creatures.
	['(elemental forces)', '(elemental force)'],
	['abyssal calamaries', 'abyssal calamary'],
	['acid blobs', 'acid blob'],
	['acolytes of darkness', 'acolyte of darkness'],
	['acolytes of the cult', 'acolyte of the cult'],
	['adepts of the cult', 'adept of the cult'],
	['adult goannas', 'adult goanna'],
	['adventurers', 'adventurer'],
	['afflicted striders', 'afflicted strider'],
	['aggressive chickens', 'aggressive chicken'],
	['agrestic chickens', 'agrestic chicken'],
	['amazons', 'amazon'],
	['ancient lion knights', 'ancient lion knight'],
	['ancient scarabs', 'ancient scarab'],
	['angry adventurers', 'angry adventurer'],
	['angry demons', 'angry demon'],
	['animated clomps', 'animated clomp'],
	['animated cyclopes', 'animated cyclops'],
	['animated feathers', 'animated feather'],
	['animated guzzlemaws', 'animated guzzlema'],
	['animated moohtants', 'animated moohtant'],
	['animated mummies', 'animated mummy'],
	['animated ogre brutes', 'animated ogre brute'],
	['animated ogre savages', 'animated ogre savage'],
	['animated ogre shamans', 'animated ogre shaman'],
	['animated rotworms', 'animated rotworm'],
	['animated skunks', 'animated skunk'],
	['animated swords', 'animated sword'],
	['arachnophobicas', 'arachnophobica'],
	['arctic fauns', 'arctic faun'],
	['armadiles', 'armadile'],
	['askarak demons', 'askarak demon'],
	['askarak lords', 'askarak lord'],
	['askarak princes', 'askarak prince'],
	['assassins', 'assassin'],
	['azure frogs', 'azure frog'],
	['badgers', 'badger'],
	['baleful bunnies', 'baleful bunny'],
	['bandits', 'bandit'],
	['banes of light', 'bane of light'],
	['banshees', 'banshee'],
	['barbarian bloodwalkers', 'barbarian bloodwalker'],
	['barbarian brutetamers', 'barbarian brutetamer'],
	['barbarian headsplitters', 'barbarian headsplitter'],
	['barbarian skullhunters', 'barbarian skullhunter'],
	['barkless devotees', 'barkless devotee'],
	['barkless fanatics', 'barkless fanatic'],
	['bashmus', 'bashmu'],
	['bats', 'bat'],
	['bears', 'bear'],
	['behemoths', 'behemoth'],
	['bellicose orgers', 'bellicose orger'],
	['berrypests', 'berrypest'],
	['berserker chickens', 'berserker chicken'],
	['betrayed wraiths', 'betrayed wraith'],
	['biting books', 'biting book'],
	['black cobras', 'black cobra'],
	['black sheep', 'black sheep'],
	['black sphinx acolytes', 'black sphinx acolyte'],
	['blazing fire elementals', 'blazing fire elemental'],
	['blemished spawns', 'blemished spawn'],
	['blightwalkers', 'blightwalker'],
	['blistering fire elementals', 'blistering fire elemental'],
	['blood beasts', 'blood beast'],
	['blood crabs', 'blood crab'],
	['blood hands', 'blood hand'],
	['blood priests', 'blood priest'],
	['blooms of doom', 'bloom of doom'],
	['blue djinns', 'blue djinn'],
	['boars', 'boar'],
	['bog frogs', 'bog frog'],
	['bog raiders', 'bog raider'],
	['bonebeasts', 'bonebeast'],
	['bonelords', 'bonelord'],
	['bony sea devils', 'bony sea devil'],
	['boogies', 'boogy'],
	['bound astral power', 'bound astral power'],
	['brachiodemons', 'brachiodemon'],
	['brain squids', 'brain squid'],
	['braindeaths', 'braindeath'],
	['branchy crawlers', 'branchy crawler'],
	['breach broods', 'breach brood'],
	['brides of night', 'bride of night'],
	['brimstone bugs', 'brimstone bug'],
	['brittle skeletons', 'brittle skeleton'],
	['broken shapers', 'broken shaper'],
	['bugs', 'bug'],
	['burning books', 'burning book'],
	['burning gladiators', 'burning gladiator'],
	['burster spectres', 'burster spectre'],
	['butterflies', 'butterfly'],
	['calamaries', 'calamary'],
	['canopic jars', 'canopic jar'],
	['capricious phantoms', 'capricious phantom'],
	['carniphilas', 'carniphila'],
	['carnisylvan saplings', 'carnisylvan sapling'],
	['carrion worms', 'carrion worm'],
	['cats', 'cat'],
	['cave chimeras', 'cave chimera'],
	['cave devourers', 'cave devourer'],
	['cave hydras', 'cave hydra'],
	['cave parrots', 'cave parrot'],
	['cave rats', 'cave rat'],
	['centipedes', 'centipede'],
	['chakoya toolshapers', 'chakoya toolshaper'],
	['chakoya tribewardens', 'chakoya tribewarden'],
	['chakoya windcallers', 'chakoya windcaller'],
	['charged disruptions', 'charged disruption'],
	['charged energy elementals', 'charged energy elemental'],
	['chargers', 'charger'],
	['charging Outburst', 'charging Outburst'],
	['chasm spawns', 'chasm spawn'],
	['chickens', 'chicken'],
	['choking fears', 'choking fear'],
	['clay guardians', 'clay guardian'],
	['cliff striders', 'cliff strider'],
	['cloaks of terror', 'cloak of terror'],
	['clomps', 'clomp'],
	['cobra assassins', 'cobra assassin'],
	['cobra scouts', 'cobra scout'],
	['cobra viziers', 'cobra vizier'],
	['cobras', 'cobra'],
	['cocoons', 'cocoon'],
	['containment crystals', 'containment crystal'],
	['containment machines', 'containment machine'],
	['control towers', 'control tower'],
	['coral frogs', 'coral frog'],
	['corrupt nagas', 'corrupt naga'],
	['corrupted souls', 'corrupted soul'],
	['corym charlatans', 'corym charlatan'],
	['corym skirmishers', 'corym skirmisher'],
	['corym vanguards', 'corym vanguard'],
	['cosmic energy prism A', 'cosmic energy prism A'],
	['cosmic energy prism B', 'cosmic energy prism B'],
	['cosmic energy prism C', 'cosmic energy prism C'],
	['cosmic energy prism D', 'cosmic energy prism D'],
	['courage leeches', 'courage leech'],
	['cows', 'cow'],
	['crabs', 'crab'],
	['cracklers', 'crackler'],
	['crawlers', 'crawler'],
	['crazed beggars', 'crazed beggar'],
	['crazed dwarfs', 'crazed dwarf'],
	['crazed summer rearguards', 'crazed summer rearguard'],
	['crazed summer vanguards', 'crazed summer vanguard'],
	['crazed winter rearguards', 'crazed winter rearguard'],
	['crazed winter vanguards', 'crazed winter vanguard'],
	['crimson frogs', 'crimson frog'],
	['crocodiles', 'crocodile'],
	['crustaceae giganticae', 'crustacea gigantica'],
	['crypt defilers', 'crypt defiler'],
	['crypt shamblers', 'crypt shambler'],
	['crypt wardens', 'crypt warden'],
	['crypt warriors', 'crypt warrior'],
	['crystal spiders', 'crystal spider'],
	['crystal wolves', 'crystal wolf'],
	['crystalcrushers', 'crystalcrusher'],
	['cult believers', 'cult believer'],
	['cult enforcers', 'cult enforcer'],
	['cult scholars', 'cult scholar'],
	['cursed books', 'cursed book'],
	['cursed prospectors', 'cursed prospector'],
	['cyclopes drone', 'cyclops drone'],
	['cyclopes smith', 'cyclops smith'],
	['cyclopes', 'cyclops'],
	['damaged crystal golems', 'damaged crystal golem'],
	['damaged worker golems', 'damaged worker golem'],
	['damned souls', 'damned soul'],
	['dark apprentices', 'dark apprentice'],
	['dark carnisylvans', 'dark carnisylvan'],
	['dark fauns', 'dark faun'],
	['dark magicians', 'dark magician'],
	['dark monks', 'dark monk'],
	['dark soul reapers', 'dark soul reaper'],
	['dark souls', 'dark soul'],
	['dark torturers', 'dark torturer'],
	['dawn bats', 'dawn bat'],
	['dawn scorpions', 'dawn scorpion'],
	['dawnfire asuras', 'dawnfire asura'],
	['dawnflies', 'dawnfly'],
	['death blobs', 'death blob'],
	['death dragons', 'death dragon'],
	['death priests', 'death priest'],
	['death reapers', 'death reaper'],
	['deathling scouts', 'deathling scout'],
	['deathling spellsingers', 'deathling spellsinger'],
	['deathslicers', 'deathslicer'],
	['deathspawns', 'deathspawn'],
	['deepling brawlers', 'deepling brawler'],
	['deepling elites', 'deepling elite'],
	['deepling guards', 'deepling guard'],
	['deepling master librarians', 'deepling master librarian'],
	['deepling scouts', 'deepling scout'],
	['deepling spellsingers', 'deepling spellsinger'],
	['deepling tyrants', 'deepling tyrant'],
	['deepling warriors', 'deepling warrior'],
	['deepling workers', 'deepling worker'],
	['deepsea blood crabs', 'deepsea blood crab'],
	['deepworms', 'deepworm'],
	['deer', 'deer'],
	['defilers', 'defiler'],
	['demon outcasts', 'demon outcast'],
	['demon parrots', 'demon parrot'],
	['demon skeletons', 'demon skeleton'],
	['demons', 'demon'],
	['depolarized cracklers', 'depolarized crackler'],
	['depowered minotaurs', 'depowered minotaur'],
	['desperate white deer', 'desperate white deer'],
	['destroyed pillars', 'destroyed pillar'],
	['destroyers', 'destroyer'],
	['devourers', 'devourer'],
	['diabolic imps', 'diabolic imp'],
	['diamond servant replicas', 'diamond servant replica'],
	['diamond servants', 'diamond servant'],
	['dire penguins', 'dire penguin'],
	['diremaws', 'diremaw'],
	['disgusting oozes', 'disgusting ooze'],
	['disruptions', 'disruption'],
	['distorted phantoms', 'distorted phantom'],
	['dogs', 'dog'],
	['domestikions', 'domestikion'],
	['doom deer', 'doom deer'],
	['doomsday cultists', 'doomsday cultist'],
	['dragon hatchlings', 'dragon hatchling'],
	['dragon lord hatchlings', 'dragon lord hatchling'],
	['dragon lords', 'dragon lord'],
	['dragon servants', 'dragon servant'],
	['dragon wraths', 'dragon wrath'],
	['dragonlings', 'dragonling'],
	['dragons', 'dragon'],
	['draken abominations', 'draken abomination'],
	['draken elites', 'draken elite'],
	['draken spellweavers', 'draken spellweaver'],
	['draken warmasters', 'draken warmaster'],
	['draptors', 'draptor'],
	['dread intruders', 'dread intruder'],
	['dread minions', 'dread minion'],
	['dreadbeasts', 'dreadbeast'],
	['drillworms', 'drillworm'],
	['dromedaries', 'dromedary'],
	['druid familiars', 'druid familiar'],
	['druid\'s apparitions', 'druid\'s apparition'],
	['duskbringers', 'duskbringer'],
	['dwarf dispensers', 'dwarf dispenser'],
	['dwarf geomancers', 'dwarf geomancer'],
	['dwarf guards', 'dwarf guard'],
	['dwarf henchmen', 'dwarf henchman'],
	['dwarf miners', 'dwarf miner'],
	['dwarf soldiers', 'dwarf soldier'],
	['dwarfs', 'dwarf'],
	['dworc fleshhunters', 'dworc fleshhunter'],
	['dworc venomsnipers', 'dworc venomsniper'],
	['dworc voodoomasters', 'dworc voodoomaster'],
	['earth elementals', 'earth elemental'],
	['earworms', 'earworm'],
	['efreet', 'efreet'],
	['eggs', 'egg'],
	['elder bonelords', 'elder bonelord'],
	['elder forest furies', 'elder forest fury'],
	['elder mummies', 'elder mummy'],
	['elder wyrms', 'elder wyrm'],
	['elephants', 'elephant'],
	['elf arcanists', 'elf arcanist'],
	['elf overseers', 'elf overseer'],
	['elf scouts', 'elf scout'],
	['elves', 'elf'],
	['emerald damselflies', 'emerald damselfly'],
	['emerald tortoises', 'emerald tortoise'],
	['empowered glooth horror', 'empowered glooth horror'],
	['energetic books', 'energetic book'],
	['energized raging mages', 'energized raging mage'],
	['energuardians of tales', 'energuardian of tales'],
	['energy elementals', 'energy elemental'],
	['energy pulse', 'energy pulse'],
	['enfeebled silencers', 'enfeebled silencer'],
	['enlighteneds of the cult', 'enlightened of the cult'],
	['enraged bookworms', 'enraged bookworm'],
	['enraged crystal golems', 'enraged crystal golem'],
	['enraged sand broods', 'enraged sand brood'],
	['enraged souls', 'enraged soul'],
	['enraged squirrels', 'enraged squirrel'],
	['enraged white deer', 'enraged white deer'],
	['enslaved dwarfs', 'enslaved dwarf'],
	['enthralled demons', 'enthralled demon'],
	['eruption of destruction', 'eruption of destruction'],
	['essences of darkness', 'essence of darkness'],
	['eternal guardians', 'eternal guardian'],
	['evil prospectors', 'evil prospector'],
	['evil sheep lord', 'evil sheep lord'],
	['evil sheep', 'evil sheep'],
	['execowtioners', 'execowtioner'],
	['exotic bats', 'exotic bat'],
	['exotic cave spiders', 'exotic cave spider'],
	['eyeless devourers', 'eyeless devourer'],
	['eyes of the seven', 'eye of the seven'],
	['falcon knights', 'falcon knight'],
	['falcon paladins', 'falcon paladin'],
	['fauns', 'faun'],
	['feeble glooth horror', 'feeble glooth horror'],
	['feral sphinxes', 'feral sphinx'],
	['feverish citizens', 'feverish citizen'],
	['feversleeps', 'feversleep'],
	['filth toads', 'filth toad'],
	['fire devils', 'fire devil'],
	['fire elementals', 'fire elemental'],
	['firestarters', 'firestarter'],
	['fish', 'fish'],
	['flames of omrafir', 'flame of Omrafir'],
	['flamethrowers', 'flamethrower'],
	['flamingos', 'flamingo'],
	['flimsy lost souls', 'flimsy lost soul'],
	['floating savants', 'floating savant'],
	['flying books', 'flying book'],
	['foam stalkers', 'foam stalker'],
	['forest furies', 'forest fury'],
	['foxes', 'fox'],
	['frazzlemaws', 'frazzlemaw'],
	['freakish lost souls', 'freakish lost soul'],
	['freed souls', 'freed soul'],
	['frost dragon hatchlings', 'frost dragon hatchling'],
	['frost dragons', 'frost dragon'],
	['frost flower asuras', 'frost flower asura'],
	['frost giantesses', 'frost giantess'],
	['frost giants', 'frost giant'],
	['frost servants', 'frost servant'],
	['frost spiders', 'frost spider'],
	['frost trolls', 'frost troll'],
	['frozen minions', 'frozen minion'],
	['fungosauruses', 'fungosaurus'],
	['furies', 'fury'],
	['furious fire elementals', 'furious fire elemental'],
	['furious trolls', 'furious troll'],
	['fury of the emperor', 'fury of the emperor'],
	['gang members', 'gang member'],
	['gargoyles', 'gargoyle'],
	['gazer spectres', 'gazer spectre'],
	['gazers', 'gazer'],
	['ghastly dragons', 'ghastly dragon'],
	['ghost wolves', 'ghost wolf'],
	['ghosts of a planegazer', 'ghost of a planegazer'],
	['ghosts', 'ghost'],
	['ghoulish hyaenas', 'ghoulish hyaena'],
	['ghouls', 'ghoul'],
	['giant spiders', 'giant spider'],
	['girtablilu warriors', 'girtablilu warrior'],
	['gladiators', 'gladiator'],
	['gloom wolves', 'gloom wolf'],
	['glooth anemones', 'glooth anemone'],
	['glooth bandits', 'glooth bandit'],
	['glooth batteries', 'glooth battery'],
	['glooth blobs', 'glooth blob'],
	['glooth bombs', 'glooth bomb'],
	['glooth brigands', 'glooth brigand'],
	['glooth golems', 'glooth golem'],
	['glooth horror', 'glooth horror'],
	['glooth mashers', 'glooth masher'],
	['glooth powered minotaurs', 'glooth-powered minotaur'],
	['glooth slashers', 'glooth slasher'],
	['glooth trashers', 'glooth trasher'],
	['glooth-generators', 'glooth generator'],
	['gnarlhounds', 'gnarlhound'],
	['gnome pack crawlers', 'gnome pack crawler'],
	['goblin assassins', 'goblin assassin'],
	['goblin leaders', 'goblin leader'],
	['goblin scavengers', 'goblin scavenger'],
	['goblins', 'goblin'],
	['golden servant replicas', 'golden servant replica'],
	['golden servants', 'golden servant'],
	['goldhanded cultist brides', 'goldhanded cultist bride'],
	['goldhanded cultists', 'goldhanded cultist'],
	['golem dispensers', 'golem dispenser'],
	['gore horns', 'gore horn'],
	['gorerillas', 'gorerilla'],
	['gozzlers', 'gozzler'],
	['grave guards', 'grave guard'],
	['grave robbers', 'grave robber'],
	['gravediggers', 'gravedigger'],
	['greater canopic jars', 'greater canopic jar'],
	['greater death minions', 'greater death minion'],
	['greater energy elementals', 'greater energy elemental'],
	['greater fire elementals', 'greater fire elemental'],
	['green djinns', 'green djinn'],
	['green frogs', 'green frog'],
	['grim reapers', 'grim reaper'],
	['grimeleeches', 'grimeleech'],
	['gryphons', 'gryphon'],
	['guardians of tales', 'guardian of tales'],
	['guzzlemaws', 'guzzlemaw'],
	['hands of cursed fate', 'hand of cursed fate'],
	['hardened usurper archers', 'hardened usurper archer'],
	['hardened usurper knights', 'hardened usurper knight'],
	['hardened usurper warlocks', 'hardened usurper warlock'],
	['haunted treelings', 'haunted treeling'],
	['hazardous phantoms', 'hazardous phantom'],
	['headpeckers', 'headpecker'],
	['hell holes', 'hell hole'],
	['hellfire fighters', 'hellfire fighter'],
	['hellflayers', 'hellflayer'],
	['hellhounds', 'hellhound'],
	['hellspawns', 'hellspawn'],
	['heralds of gloom', 'herald of gloom'],
	['heroes', 'hero'],
	['hibernal moths', 'hibernal moth'],
	['hideous fungi', 'hideous fungus'],
	['high voltage elementals', 'high voltage elemental'],
	['hive overseers', 'hive overseer'],
	['hive pores', 'hive pore'],
	['holy bog frogs', 'holy bog frog'],
	['honour guards', 'honour guard'],
	['hoodinions', 'hoodinion'],
	['horses', 'horse'],
	['hot dogs', 'hot dog'],
	['hulking carnisylvans', 'hulking carnisylvan'],
	['hulking prehemoths', 'hulking prehemoth'],
	['humongous fungi', 'humongous fungus'],
	['humorless fungi', 'humorless fungus'],
	['hunger worms', 'hunger worm'],
	['hunters', 'hunter'],
	['huskies', 'husky'],
	['hyaenas', 'hyaena'],
	['hydras', 'hydra'],
	['ice golems', 'ice golem'],
	['ice witches', 'ice witch'],
	['icecold books', 'icecold book'],
	['icicles', 'icicle'],
	['infected weepers', 'infected weeper'],
	['infernal demons', 'infernal demon'],
	['infernal frogs', 'infernal frog'],
	['infernal phantoms', 'infernal phantom'],
	['infernalists', 'infernalist'],
	['ink blobs', 'ink blob'],
	['insane sirens', 'insane siren'],
	['insect swarms', 'insect swarm'],
	['insectoid scouts', 'insectoid scout'],
	['insectoid workers', 'insectoid worker'],
	['instable breach broods', 'instable breach brood'],
	['instable sparkions', 'instable sparkion'],
	['iron servant replicas', 'iron servant replica'],
	['iron servants', 'iron servant'],
	['ironblights', 'ironblight'],
	['island trolls', 'island troll'],
	['jagged earth elementals', 'jagged earth elemental'],
	['jellyfish', 'jellyfish'],
	['juggernauts', 'juggernaut'],
	['jungle moas', 'jungle moa'],
	['juvenile bashmus', 'juvenile bashmu'],
	['juvenile cyclopes', 'juvenile cyclops'],
	['killer caimans', 'killer caiman'],
	['killer rabbits', 'killer rabbit'],
	['knight familiars', 'knight familiar'],
	['knight\'s apparitions', 'knight\'s apparition'],
	['knowledge elementals', 'knowledge elemental'],
	['knowledge raiders', 'knowledge raider'],
	['kollos', 'kollos'],
	['kongras', 'kongra'],
	['lacewing moths', 'lacewing moth'],
	['ladybugs', 'ladybug'],
	['lamassus', 'lamassu'],
	['lancer beetles', 'lancer beetle'],
	['larvas', 'larva'],
	['lava golems', 'lava golem'],
	['lava lurker attendants', 'lava lurker attendant'],
	['lava lurkers', 'lava lurker'],
	['lavafungi', 'lavafungus'],
	['lavaholes', 'lavahole'],
	['lavaworms', 'lavaworm'],
	['leaf golems', 'leaf golem'],
	['lesser death minions', 'lesser death minion'],
	['lesser fire devils', 'lesser fire devil'],
	['lesser magma crystals', 'lesser magma crystal'],
	['lesser swarmers', 'lesser swarmer'],
	['liches', 'lich'],
	['lion archers', 'lion archer'],
	['lion commanders', 'lion commander'],
	['lion knights', 'lion knight'],
	['lion warlocks', 'lion warlock'],
	['lions', 'lion'],
	['little corym charlatans', 'little corym charlatan'],
	['lizard chosens', 'lizard chosen'],
	['lizard dragon priests', 'lizard dragon priest'],
	['lizard high guards', 'lizard high guard'],
	['lizard legionnaires', 'lizard legionnaire'],
	['lizard magistratuses', 'lizard magistratus'],
	['lizard nobles', 'lizard noble'],
	['lizard sentinels', 'lizard sentinel'],
	['lizard snakecharmers', 'lizard snakecharmer'],
	['lizard templars', 'lizard templar'],
	['lizard zaoguns', 'lizard zaogun'],
	['lonely frazzlemaws', 'lonely frazzlemaw'],
	['loricate orgers', 'loricate orger'],
	['lost bashers', 'lost basher'],
	['lost berserkers', 'lost berserker'],
	['lost exiles', 'lost exile'],
	['lost ghosts of a planegazer', 'lost ghost of a planegazer'],
	['lost gnomes', 'lost gnome'],
	['lost hushers', 'lost husher'],
	['lost souls', 'lost soul'],
	['lost throwers', 'lost thrower'],
	['lost times', 'lost time'],
	['lucifuga araneas', 'lucifuga aranea'],
	['lumbering carnivors', 'lumbering carnivor'],
	['mad scientists', 'mad scientist'],
	['mad sheep', 'mad sheep'],
	['magic pillars', 'magic pillar'],
	['magical spheres', 'magical sphere'],
	['magicthrowers', 'magicthrower'],
	['magma crawlers', 'magma crawler'],
	['magma crystals', 'magma crystal'],
	['makaras', 'makara'],
	['makeshift homes', 'makeshift home'],
	['mammoths', 'mammoth'],
	['manta rays', 'manta ray'],
	['manticores', 'manticore'],
	['mantosauruses', 'mantosaurus'],
	['many faces', 'many faces'],
	['marid', 'marid'],
	['marsh stalkers', 'marsh stalker'],
	['massive earth elementals', 'massive earth elemental'],
	['massive energy elementals', 'massive energy elemental'],
	['massive fire elementals', 'massive fire elemental'],
	['massive water elementals', 'massive water elemental'],
	['meadow striders', 'meadow strider'],
	['mean lost souls', 'mean lost soul'],
	['mean maws', 'mean maw'],
	['mean minions', 'mean minion'],
	['mearidions', 'mearidion'],
	['mechanical fighters', 'mechanical fighter'],
	['medusae', 'medusa'],
	['memories of a banshee', 'memory of a banshee'],
	['memories of a book', 'memory of a book'],
	['memories of a carnisylvan', 'memory of a carnisylvan'],
	['memories of a dwarf', 'memory of a dwarf'],
	['memories of a faun', 'memory of a faun'],
	['memories of a frazzlemaw', 'memory of a frazzlemaw'],
	['memories of a fungus', 'memory of a fungus'],
	['memories of a golem', 'memory of a golem'],
	['memories of a hero', 'memory of a hero'],
	['memories of a hydra', 'memory of a hydra'],
	['memories of a lizard', 'memory of a lizard'],
	['memories of a mammoth', 'memory of a mammoth'],
	['memories of a manticore', 'memory of a manticore'],
	['memories of a pirate', 'memory of a pirate'],
	['memories of a scarab', 'memory of a scarab'],
	['memories of a shaper', 'memory of a shaper'],
	['memories of a vampire', 'memory of a vampire'],
	['memories of a werelion', 'memory of a werelion'],
	['memories of a wolf', 'memory of a wolf'],
	['memories of a yalahari', 'memory of a yalahari'],
	['memories of an amazon', 'memory of an amazon'],
	['memories of an elf', 'memory of an elf'],
	['memories of an insectoid', 'memory of an insectoid'],
	['memories of an ogre', 'memory of an ogre'],
	['menacing carnivors', 'menacing carnivor'],
	['mercurial menaces', 'mercurial menace'],
	['mercury blobs', 'mercury blob'],
	['merlkins', 'merlkin'],
	['metal gargoyles', 'metal gargoyle'],
	['midnight asuras', 'midnight asura'],
	['midnight panthers', 'midnight panther'],
	['midnight spawns', 'midnight spawn'],
	['midnight warriors', 'midnight warrior'],
	['minions of Gaz\'haragoth', 'minion of Gaz\'haragoth'],
	['minions of Versperoth', 'minion of Versperoth'],
	['minotaur amazons', 'minotaur amazon'],
	['minotaur archers', 'minotaur archer'],
	['minotaur bruisers', 'minotaur bruiser'],
	['minotaur cult followers', 'minotaur cult follower'],
	['minotaur cult prophets', 'minotaur cult prophet'],
	['minotaur cult zealots', 'minotaur cult zealot'],
	['minotaur guards', 'minotaur guard'],
	['minotaur hunters', 'minotaur hunter'],
	['minotaur idols', 'minotaur idol'],
	['minotaur invaders', 'minotaur invader'],
	['minotaur mages', 'minotaur mage'],
	['minotaur occultists', 'minotaur occultist'],
	['minotaur poachers', 'minotaur poacher'],
	['minotaur totems', 'minotaur totem'],
	['minotaurs', 'minotaur'],
	['mirror images', 'mirror image'],
	['misguided bullies', 'misguided bully'],
	['misguided shadows', 'misguided shadow'],
	['misguided thieves', 'misguided thief'],
	['modified gnarlhounds', 'modified gnarlhound'],
	['moles', 'mole'],
	['monks of the order', 'monk of the order'],
	['monks', 'monk'],
	['mooh\'tah warriors', 'mooh\'tah warrior'],
	['moohtant wallbreakers', 'moohtant wallbreaker'],
	['moohtants', 'moohtant'],
	['mould phantoms', 'mould phantom'],
	['mountain trolls', 'mountain troll'],
	['muddy earth elementals', 'muddy earth elemental'],
	['muglex clan assassins', 'muglex clan assassin'],
	['muglex clan feetman', 'muglex clan feetman'],
	['muglex clan scavengers', 'muglex clan scavenger'],
	['mummies', 'mummy'],
	['murmillions', 'murmillion'],
	['museum stone golems', 'museum stone golem'],
	['museum stone rhinos', 'museum stone rhino'],
	['mushroom sniffers', 'mushroom sniffer'],
	['mutated bats', 'mutated bat'],
	['mutated humans', 'mutated human'],
	['mutated rats', 'mutated rat'],
	['mutated tigers', 'mutated tiger'],
	['mystic energy', 'mystic energy'],
	['naga archers', 'naga archer'],
	['naga warriors', 'naga warrior'],
	['necromancer servants', 'necromancer servant'],
	['necromancers', 'necromancer'],
	['necromantic energy', 'necromantic energy'],
	['necromantic focuses', 'necromantic focus'],
	['neutral deepling warriors', 'neutral deepling warrior'],
	['nightfiends', 'nightfiend'],
	['nighthunters', 'nighthunter'],
	['nightmare scions', 'nightmare scion'],
	['nightmares of Gaz\'haragoth', 'nightmare of Gaz\'haragoth'],
	['nightmares', 'nightmare'],
	['nightslayers', 'nightslayer'],
	['nightstalkers', 'nightstalker'],
	['noble lions', 'noble lion'],
	['nomads', 'nomad'],
	['northern pikes', 'northern pike'],
	['novices of the cult', 'novice of the cult'],
	['noxious ripptors', 'noxious ripptor'],
	['nymphs', 'nymph'],
	['ogre brutes', 'ogre brute'],
	['ogre rowdies', 'ogre rowdy'],
	['ogre ruffians', 'ogre ruffian'],
	['ogre sages', 'ogre sage'],
	['ogre savages', 'ogre savage'],
	['ogre shamans', 'ogre shaman'],
	['omnivoras', 'omnivora'],
	['orc berserkers', 'orc berserker'],
	['orc cult fanatics', 'orc cult fanatic'],
	['orc cult inquisitors', 'orc cult inquisitor'],
	['orc cult minions', 'orc cult minion'],
	['orc cult priests', 'orc cult priest'],
	['orc cultists', 'orc cultist'],
	['orc leaders', 'orc leader'],
	['orc marauders', 'orc marauder'],
	['orc riders', 'orc rider'],
	['orc shamans', 'orc shaman'],
	['orc spearmen', 'orc spearman'],
	['orc warlords', 'orc warlord'],
	['orc warriors', 'orc warrior'],
	['orchid frogs', 'orchid frog'],
	['orclops doomhaulers', 'orclops doomhauler'],
	['orclops ravagers', 'orclops ravager'],
	['orcs', 'orc'],
	['orewalkers', 'orewalker'],
	['orgers', 'orger'],
	['overcharged disruptions', 'overcharged disruption'],
	['overcharged energy elements', 'overcharged energy element'],
	['overcharges', 'overcharge'],
	['paladin familiars', 'paladin familiar'],
	['paladin\'s apparitions', 'paladin\'s apparition'],
	['pandas', 'panda'],
	['parasites', 'parasite'],
	['parders', 'parder'],
	['parrots', 'parrot'],
	['party skeletons', 'party skeleton'],
	['penguins', 'penguin'],
	['phantasms', 'phantasm'],
	['pigeons', 'pigeon'],
	['pigs', 'pig'],
	['pillars of death', 'pillar of death'],
	['pillars of draining', 'pillar of draining'],
	['pillars of healing', 'pillar of healing'],
	['pillars of protection', 'pillar of protection'],
	['pillars of summoning', 'pillar of summoning'],
	['pirat bombardiers', 'pirat bombardier'],
	['pirat cutthroats', 'pirat cutthroat'],
	['pirat mates', 'pirat mate'],
	['pirat scoundrels', 'pirat scoundrel'],
	['pirate buccaneers', 'pirate buccaneer'],
	['pirate corsairs', 'pirate corsair'],
	['pirate cutthroats', 'pirate cutthroat'],
	['pirate ghosts', 'pirate ghost'],
	['pirate marauders', 'pirate marauder'],
	['pirate skeletons', 'pirate skeleton'],
	['pixies', 'pixie'],
	['plaguesmiths', 'plaguesmith'],
	['plaguethrowers', 'plaguethrower'],
	['planedweller', 'planedweller'],
	['players', 'player'],
	['plunder patriarches', 'plunder patriarch'],
	['poachers', 'poacher'],
	['poison spiders', 'poison spider'],
	['poisonous carnisylvans', 'poisonous carnisylvan'],
	['polar bears', 'polar bear'],
	['poodles', 'poodle'],
	['pookas', 'pooka'],
	['possessed trees', 'possessed tree'],
	['priestesses of the wild sun', 'priestess of the wild sun'],
	['priestesses', 'priestess'],
	['primal pack beasts', 'primal pack beast'],
	['putrid mummies', 'putrid mummy'],
	['quara constrictor scouts', 'quara constrictor scout'],
	['quara constrictors', 'quara constrictor'],
	['quara hydromancer scouts', 'quara hydromancer scout'],
	['quara hydromancers', 'quara hydromancer'],
	['quara mantassin scouts', 'quara mantassin scout'],
	['quara mantassins', 'quara mantassin'],
	['quara pincher scouts', 'quara pincher scout'],
	['quara pinchers', 'quara pincher'],
	['quara predator scouts', 'quara predator scout'],
	['quara predators', 'quara predator'],
	['rabbits', 'rabbit'],
	['rage squids', 'rage squid'],
	['raging fires', 'raging fire'],
	['rats', 'rat'],
	['ravenous lava lurkers', 'ravenous lava lurker'],
	['reality reaver', 'reality reaver'],
	['reality reavers', 'reality reavers'], // Note: Intentionally left pluralized since there is already a separate `reality reaver` entry.
	['redeemed souls', 'redeemed soul'],
	['reflections of a Mage', 'reflection of a Mage'],
	['reflections of Mawhawk', 'reflection of Mawhawk'],
	['reflections of Obujos', 'reflection of Obujos'],
	['renegade knights', 'renegade knight'],
	['renegade quara constrictors', 'renegade quara constrictor'],
	['renegade quara hydromancers', 'renegade quara hydromancer'],
	['renegade quara mantassins', 'renegade quara mantassin'],
	['renegade quara pinchers', 'renegade quara pincher'],
	['renegade quara predators', 'renegade quara predator'],
	['retching horrors', 'retching horror'],
	['rift broods', 'rift brood'],
	['rift fragments', 'rift fragment'],
	['rift invaders', 'rift invader'],
	['rift scythes', 'rift scythe'],
	['rift worms', 'rift worm'],
	['ripper spectres', 'ripper spectre'],
	['roaring lions', 'roaring lion'],
	['roaring water elementals', 'roaring water elemental'],
	['roast porks', 'roast pork'],
	['rogue nagas', 'rogue naga'],
	['rorcs', 'rorc'],
	['rot elementals', 'rot elemental'],
	['rotten golems', 'rotten golem'],
	['rotworms', 'rotworm'],
	['rustheap golems', 'rustheap golem'],
	['sabreteeth', 'sabretooth'],
	['sacred snakes', 'sacred snake'],
	['sacred spiders', 'sacred spider'],
	['salamander trainers', 'salamander trainer'],
	['salamanders', 'salamander'],
	['sand broods', 'sand brood'],
	['sand vortexes', 'sand vortex'],
	['sandcrawlers', 'sandcrawler'],
	['sandstone scorpions', 'sandstone scorpion'],
	['scar tribe shamans', 'scar tribe shaman'],
	['scar tribe warriors', 'scar tribe warrior'],
	['scarabs', 'scarab'],
	['scissorions', 'scissorion'],
	['scorn of the emperor', 'scorn of the emperor'],
	['scorpions', 'scorpion'],
	['sea serpents', 'sea serpent'],
	['seacrest serpents', 'seacrest serpent'],
	['seagulls', 'seagull'],
	['security golems', 'security golem'],
	['serpent spawns', 'serpent spawn'],
	['servants of Tentugly', 'servant of Tentugly'],
	['shaburak demons', 'shaburak demon'],
	['shaburak lords', 'shaburak lord'],
	['shaburak princes', 'shaburak prince'],
	['shadow fiends', 'shadow fiend'],
	['shadow hounds', 'shadow hound'],
	['shadow pupils', 'shadow pupil'],
	['shadow tentacles', 'shadow tentacle'],
	['shaper matriarches', 'shaper matriarch'],
	['sharks', 'shark'],
	['sheep', 'sheep'],
	['shimmying butterflies', 'shimmying butterfly'],
	['shiversleeps', 'shiversleep'],
	['shock heads', 'shock head'],
	['shredderthrowers', 'shredderthrower'],
	['shrieking cry-stals', 'shrieking cry-stal'],
	['sibangs', 'sibang'],
	['sights of surrender', 'sight of surrender'],
	['silencers', 'silencer'],
	['silver rabbits', 'silver rabbit'],
	['skeleton elite warriors', 'skeleton elite warrior'],
	['skeleton warriors', 'skeleton warrior'],
	['skeletons', 'skeleton'],
	['skunks', 'skunk'],
	['slick water elementals', 'slick water elemental'],
	['slimes', 'slime'],
	['slippery northern pikes', 'slippery northern pike'],
	['slugs', 'slug'],
	['smugglers', 'smuggler'],
	['snake god essence', 'snake god essence'],
	['snakes', 'snake'],
	['solitary frost dragons', 'solitary frost dragon'],
	['sons of verminor', 'son of Verminor'],
	['sorcerer familiars', 'sorcerer familiar'],
	['sorcerer\'s apparitions', 'sorcerer\'s apparition'],
	['soul reapers', 'soul reaper'],
	['soul sparks', 'soul spark'],
	['soul-broken harbingers', 'soul-broken harbinger'],
	['soulcatchers', 'soulcatcher'],
	['souleaters', 'souleater'],
	['sparkions', 'sparkion'],
	['sparks of destruction', 'spark of destruction'],
	['spawns of Devovorga', 'spawn of Devovorga'],
	['spectres', 'spectre'],
	['spheres of wrath', 'sphere of wrath'],
	['sphinxes', 'sphinx'],
	['spiders', 'spider'],
	['spidris elite', 'spidris elite'],
	['spidris', 'spidris'],
	['spiky carnivors', 'spiky carnivor'],
	['spit nettles', 'spit nettle'],
	['spitters', 'spitter'],
	['spyrats', 'spyrat'],
	['squid wardens', 'squid warden'],
	['squidgy slimes', 'squidgy slime'],
	['squirrels', 'squirrel'],
	['stabilizing dread intruders', 'stabilizing dread intruder'],
	['stabilizing reality reavers', 'stabilizing reality reaver'],
	['stalkers', 'stalker'],
	['stalking stalks', 'stalking stalk'],
	['stampors', 'stampor'],
	['starving wolves', 'starving wolf'],
	['stone devourers', 'stone devourer'],
	['stone golems', 'stone golem'],
	['stone rhinos', 'stone rhino'],
	['stonerefiners', 'stonerefiner'],
	['strange rats', 'strange rat'],
	['strange slimes', 'strange slime'],
	['streaked devourers', 'streaked devourer'],
	['strong glooth horror', 'strong glooth horror'],
	['sulphiders', 'sulphider'],
	['sulphur geysirs', 'sulphur geysir'],
	['sulphur spouters', 'sulphur spouter'],
	['sun-marked goannas', 'sun-marked goanna'],
	['superior death minion', 'superior death minion'],
	['swamp trolls', 'swamp troll'],
	['swamplings', 'swampling'],
	['swan maidens', 'swan maiden'],
	['swarmer hatchlings', 'swarmer hatchling'],
	['swarmers', 'swarmer'],
	['swords of vengeance', 'sword of vengeance'],
	['symbols of fear', 'symbol of fear'],
	['symbols of hatred', 'symbol of hatred'],
	['tainted souls', 'tainted soul'],
	['tarantulas', 'tarantula'],
	['tarnished spirits', 'tarnished spirit'],
	['terramites', 'terramite'],
	['terrified elephants', 'terrified elephant'],
	['terror birds', 'terror bird'],
	['terrorsleeps', 'terrorsleep'],
	['thanatursuses', 'thanatursus'],
	['thieves', 'thief'],
	['thieving squirrels', 'thieving squirrel'],
	['thorn minions', 'thorn minion'],
	['thorn steeds', 'thorn steed'],
	['thornback tortoises', 'thornback tortoise'],
	['thornfire wolves', 'thornfire wolf'],
	['tigers', 'tiger'],
	['time keepers', 'time keeper'],
	['time wasters', 'time waster'],
	['toads', 'toad'],
	['tomb servants', 'tomb servant'],
	['tormented ghosts', 'tormented ghost'],
	['tortoises', 'tortoise'],
	['toxic swarms', 'toxic swarm'],
	['travelling merchants', 'travelling merchant'],
	['tremendous tyrants', 'tremendous tyrant'],
	['tremor worms', 'tremor worm'],
	['troll champions', 'troll champion'],
	['troll guards', 'troll guard'],
	['troll legionnaires', 'troll legionnaire'],
	['troll marauders', 'troll marauder'],
	['troll-trained salamanders', 'troll-trained salamander'],
	['trolls', 'troll'],
	['true dawnfire asuras', 'true dawnfire asura'],
	['true frost flower asuras', 'true frost flower asura'],
	['true midnight asuras', 'true midnight asura'],
	['tunnel devourers', 'tunnel devourer'],
	['tunnel tyrants', 'tunnel tyrant'],
	['turbulent elementals', 'turbulent elemental'],
	['twisted pookas', 'twisted pooka'],
	['twisted shapers', 'twisted shaper'],
	['two-headed turtles', 'two-headed turtle'],
	['ugly monsters', 'ugly monster'],
	['unbound blightwalkers', 'unbound blightwalker'],
	['unbound defilers', 'unbound defiler'],
	['unbound demon outcasts', 'unbound demon outcast'],
	['unbound demons', 'unbound demon'],
	['undead cavebears', 'undead cavebear'],
	['undead dragons', 'undead dragon'],
	['undead elite gladiators', 'undead elite gladiator'],
	['undead gladiators', 'undead gladiator'],
	['undead mine workers', 'undead mine worker'],
	['undead prospectors', 'undead prospector'],
	['undertakers', 'undertaker'],
	['unstable sparks', 'unstable spark'],
	['unstable tunnels', 'unstable tunnel'],
	['usurper archers', 'usurper archer'],
	['usurper commanders', 'usurper commander'],
	['usurper knights', 'usurper knight'],
	['usurper warlocks', 'usurper warlock'],
	['valkyries', 'valkyrie'],
	['vampire brides', 'vampire bride'],
	['vampire pigs', 'vampire pig'],
	['vampire viscounts', 'vampire viscount'],
	['vampires', 'vampire'],
	['varnished diremaws', 'varnished diremaw'],
	['venerable foam stalkers', 'venerable foam stalker'],
	['venerable girtablilus', 'venerable girtablilu'],
	['vermin swarms', 'vermin swarm'],
	['vexclaws', 'vexclaw'],
	['vibrant phantoms', 'vibrant phantom'],
	['vicious liches', 'vicious lich'],
	['vicious manbats', 'vicious manbat'],
	['vicious squires', 'vicious squire'],
	['vile destroyers', 'vile destroyer'],
	['vile grandmasters', 'vile grandmaster'],
	['voidshards', 'voidshard'],
	['vulcongras', 'vulcongra'],
	['vulnerable cocoons', 'vulnerable cocoon'],
	['wailing widows', 'wailing widow'],
	['walkers', 'walker'],
	['war golems', 'war golem'],
	['war wolves', 'war wolf'],
	['warlocks', 'warlock'],
	['waspoids', 'waspoid'],
	['wasps', 'wasp'],
	['water buffalos', 'water buffalo'],
	['water elementals', 'water elemental'],
	['weakened demons', 'weakened demon'],
	['weakened frazzlemaws', 'weakened frazzlemaw'],
	['weakened glooth horror', 'weakened glooth horror'],
	['weepers', 'weeper'],
	['werebadgers', 'werebadger'],
	['werebears', 'werebear'],
	['wereboars', 'wereboar'],
	['werefoxes', 'werefox'],
	['werehyaena shamans', 'werehyaena shaman'],
	['werehyaenas', 'werehyaena'],
	['werelionesses', 'werelioness'],
	['werelions', 'werelion'],
	['werewolves', 'werewolf'],
	['white deer', 'white deer'],
	['white lions', 'white lion'],
	['white shades', 'white shade'],
	['wigglers', 'wiggler'],
	['wild dogs', 'wild dog'],
	['wild horses', 'wild horse'],
	['wild warriors', 'wild warrior'],
	['wilting leaf golems', 'wilting leaf golem'],
	['winter wolves', 'winter wolf'],
	['wisps', 'wisp'],
	['witches', 'witch'],
	['wolves', 'wolf'],
	['woodlings', 'woodling'],
	['worker golems', 'worker golem'],
	['worm priestesses', 'worm priestess'],
	['wyrms', 'wyrm'],
	['wyverns', 'wyvern'],
	['yalahari despoilers', 'yalahari despoiler'],
	['yetis', 'yeti'],
	['yielothax', 'yielothax'],
	['young goannas', 'young goanna'],
	['young sea serpents', 'young sea serpent'],
	['young trolls', 'young troll'],
	['zombies', 'zombie'],
]);

const prettyToNormalizedNames = new Map();
for (const [killStatsName, prettyName] of normalizedToPrettyNames) {
	prettyToNormalizedNames.set(prettyName, killStatsName);
}

export const toPrettyName = (killStatsName) => {
	const prettyName = normalizedToPrettyNames.get(killStatsName);
	return prettyName;
};

export const toKillStatsName = (prettyName) => {
	const killStatsName = normalizedToPrettyNames.get(prettyName);
	return killStatsName;
};

const test = async () => {
	const readKillStatNames = async () => {
		const filePath = './data/_global-total/names.json';
		const json = await fs.readFile(filePath);
		const array = JSON.parse(json);
		const set = new Set(array);
		return set;
	};

	const KILL_STAT_NAMES = await readKillStatNames();

	for (const [killStatsName, prettyName] of normalizedToPrettyNames) {
		console.assert(KILL_STAT_NAMES.has(killStatsName), `Expected ${killStatsName} to appear in global kill stats.`);
		if (killStatsName !== prettyName) {
			console.assert(!KILL_STAT_NAMES.has(prettyName), `Expected ${prettyName} to NOT appear in global kill stats.`);
		}
	}

	for (const race of KILL_STAT_NAMES) {
		console.assert(normalizedToPrettyNames.has(race), `Missing normalization map entry: ${race}`);
	}
};

if (process.env.TEST) {
	await test();
}
